### ISSUE TITLE
Revolver.to_a should call @array.dup

### ISSUE THREAD

**Issue by aduncan** [citizen428/revolver#2]
r = Revolver.from_array([*1..3], 3)
initial_size = r.size
r.to_a.pop
final_size = r.size
puts "uh-oh" unless final_size == initial_size

**Comment by citizen428** [comment]
Thanks! Fixed. Will write a test with your example tonight and then push a new version.

**Comment by citizen428** [comment]
Managed to steal a couple of minutes time at work, new version pushed.
